<?php
/**
* Implementation of hook_block
*/

//~ drupal_add_js(drupal_get_path('module', 'jobhistoryfield').'/jobhistoryfield.js');

function user_relationships_extras_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == "list") {
    // Generate listing of blocks from this module, for the admin/block page
    $block = array();
    $block[0]["info"] = t('Mutual Contacts');
    $block[1]["info"] = t('People You Might Know');
    $block[2]["info"] = t('Facebook-Style Status Form');
    $block[3]["info"] = t('Pending Contact Requests');
    return $block;
  } // end if
  else if($op == 'view' && $delta == 0) {
    /**
     * Mutual Contacts
     */
    $output = '';
    global $user;
    $suggested_contacts = array();
    //~ check to see if user is not anonymous and not viewing his own profile
    if ($user->uid > 0 && get_uid_from_url() != $user->uid)
      $current_user = $user->uid;
    else
      return;
    $relationship_status = '1';
    //~ $tolerance = 4;
    $list_size = 3;
    $viewed_user = get_uid_from_url();
    $result = db_query('SELECT user_relationships.rid AS rid,
                        users_user_relationships.name AS name,
                        users_user_relationships.uid AS uid,
                        users_user_relationships.picture AS picture,
                        user_relationship_types_user_relationships.plural_name AS plural_name,
                        roles.rid AS role,
                        RAND() as _random
                        FROM {user_relationships} user_relationships 
                        LEFT JOIN {users} users_user_relationships ON user_relationships.requestee_id = users_user_relationships.uid
                        LEFT JOIN {users} users_user_relationships_1 ON user_relationships.requester_id = users_user_relationships_1.uid
                        LEFT JOIN {users_roles} roles ON roles.uid = users_user_relationships.uid
                        LEFT JOIN {user_relationship_types} user_relationship_types_user_relationships ON user_relationships.rtid = user_relationship_types_user_relationships.rtid
                        WHERE (user_relationships.approved = "%s") AND (user_relationships.requester_id = %d)
                        ORDER BY _random ASC', $relationship_status, $viewed_user
    );
    while ($row = db_fetch_object($result)) {
      if (!(in_array($row->uid, $suggested_contacts)))
        $relationship = db_query('SELECT rid FROM {user_relationships} WHERE (requestee_id = %d AND requester_id = %d) OR (requestee_id = %d AND requester_id = %d)', $current_user, $row->uid, $row->uid, $current_user);
      if (((db_fetch_object($relationship))) && (!($current_user == $row->uid)) && $row->role == 4) {
        $suggested_contacts[] = $row->uid;
      }
      if (count($suggested_contacts) >= $list_size)
        break(1);
    }
    // if (empty($suggested_contacts))
      // $output .= t('No Mutual Contacts');

    foreach ($suggested_contacts as $suggested) {
      $output .= _theme_contact_small($suggested);
    }
    // set up the block
    $block = array();
    $block['subject'] = 'Mutual Contacts';
    $block['content'] = $output;
    return $block;
  } 
  else if($op == 'view' && $delta == 1) {
    /**
     * People You Might Know
     */
    $output = '';
    global $user;
    //~ check for anonymous users
    if ($user->uid > 0)
      $current_user = $user->uid;
    else
      return;
    $relationship_status = '1';
    $tolerance = 4;
    $list_size = 3;
    
    //~ Create array of contacts
    $result = db_query_range('SELECT user_relationships.rid AS rid,
                        users_user_relationships.name AS name,
                        users_user_relationships.uid AS uid,
                        users_user_relationships.picture AS picture,
                        user_relationship_types_user_relationships.plural_name AS plural_name,
                        roles.rid AS role,
                        RAND() as _random
                        FROM {user_relationships} user_relationships 
                        LEFT JOIN {users} users_user_relationships ON user_relationships.requestee_id = users_user_relationships.uid
                        LEFT JOIN {users} users_user_relationships_1 ON user_relationships.requester_id = users_user_relationships_1.uid
                        LEFT JOIN {users_roles} roles ON roles.uid = users_user_relationships.uid
                        LEFT JOIN {user_relationship_types} user_relationship_types_user_relationships ON user_relationships.rtid = user_relationship_types_user_relationships.rtid
                        WHERE (user_relationships.approved = "%s") AND (user_relationships.requester_id = %d)
												GROUP by users_user_relationships.uid
                        ORDER BY _random ASC', $relationship_status, $current_user, 0, $tolerance);
    
    while ($row = db_fetch_object($result)) {
      if ($row->role == 4)
        $contacts[] = $row->uid;
    }
  
    $suggested_contacts = array();
    
    $current = 0;
    while (isset($contacts[$current])) {
      $result = db_query('SELECT user_relationships.rid AS rid,
                        users_user_relationships.name AS name,
                        users_user_relationships.uid AS uid,
                        users_user_relationships.picture AS picture,
                        user_relationship_types_user_relationships.plural_name AS plural_name,
                        roles.rid AS role,
                        RAND() as _random
                        FROM {user_relationships} user_relationships 
                        LEFT JOIN {users} users_user_relationships ON user_relationships.requestee_id = users_user_relationships.uid
                        LEFT JOIN {users} users_user_relationships_1 ON user_relationships.requester_id = users_user_relationships_1.uid
                        LEFT JOIN {users_roles} roles ON roles.uid = users_user_relationships.uid
                        LEFT JOIN {user_relationship_types} user_relationship_types_user_relationships ON user_relationships.rtid = user_relationship_types_user_relationships.rtid
                        WHERE (user_relationships.approved = "%s") AND (user_relationships.requester_id = %d)
                        ORDER BY _random ASC', $relationship_status, $contacts[$current]
      );

      while ($row = db_fetch_object($result)) {
        if (!(in_array($row->uid, $suggested_contacts)))

          //~ Test if current user is already contacts
          //~ $relationship = user_relationships_type_load(267, NULL);
          $relationship = db_query('SELECT rid FROM {user_relationships} WHERE (requestee_id = %d AND requester_id = %d) OR (requestee_id = %d AND requester_id = %d)', $current_user, $row->uid, $row->uid, $current_user);
          if ((!(db_fetch_object($relationship))) && (!($current_user == $row->uid)) && $row->role == 4) {
            $suggested_contacts[] = $row->uid;
          }
        if (count($suggested_contacts) >= $list_size)
          break(2);
      }
      $current++;
    }
    
    if (empty($suggested_contacts))
      $output .= t('No Suggestions');

    foreach ($suggested_contacts as $suggested) {
      $output .= _theme_contact_full($suggested);
    }

    $block = array();
    $block['subject'] = 'People You Might Know';
    $block['content'] = $output;
    return $block;
  }
  else if($op == 'view' && $delta == 2) {
    /**
     * Facebook-Style Status Form
     */
    global $user;
    //~ Make sure only applicants can see this
    if(!in_array('applicant', $user->roles)) return;
    $output = 'Set new status: ';
    $output .= theme('facebook_status_form_display', user_load(get_uid_from_url()));

    $block = array();
    $block['subject'] = '';
    $block['content'] = $output;
    return $block;
  }
  else if($op == 'view' && $delta == 3) {
    
    $output = '';
    
    //Relationship Requests Block
    global $user;
    
    $relationships = user_relationships_load(array('user' => $user->uid, 'requestee_id' => $user->uid, 'approved' => FALSE), array('include_user_info' => TRUE));
    
    //~ print_r(arg(1));
    
    if ((count($relationships) > 0) && (arg(1) == $user->uid)) {
      //~ print_r($relationships);
      foreach ($relationships as $relationship) {
        $output .= '<br />'._theme_contact_full($relationship->requester_id, $name = TRUE, $user_relationship = $relationship);
      }
    
      $block['subject'] = 'Pending Contact Requests';
      $block['content'] = $output;
      //~ $block['content'] = 'test';
    }
    else {
      $block['subject'] = '';
      $block['content'] = '';
    }
    return $block;
  }
} // end user_relationships_extras_block


/**
 * Implementation of hook_theme().
 */
function user_relationships_extras_theme() {

  return array(
    'contact_small' => array(
      'arguments' => array('uid' => NULL)
    ),

    /*// Theme article heartbeat node
    'heartbeat_article' => array(
      'arguments' => array('message' => NULL, 'node' => NULL)
    ),
    
    // Theme Showcase heartbeat node
    'heartbeat_showcase_item' => array(
      'arguments' => array('message' => NULL, 'node' => NULL)
    ),

    // Theme agenda or event group post
    'heartbeat_event' => array(
      'arguments' => array('message' => NULL, 'node' => NULL)
    ),

    // Theme album group post
    'heartbeat_album' => array(
      'arguments' => array('message' => NULL, 'node' => NULL)
    ),

    // Video content box
    'heartbeat_video' => array(
      'arguments' => array('nid' => NULL,'movie' => NULL, 'image' => NULL)
    ),

    // Friends box
    'heartbeat_friends' => array(
      'arguments' => array('message' => NULL)
    ),/**/
  );
}

/**
 * Theme function for a heartbeat article
 */
function theme_contact_small($uid) {
  //~ usage: theme('heartbeat_group_post', $uid);
  $output = '';
  
  return $output;
}
